<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Please enter surname</name>
   <tag></tag>
   <elementGuidId>f5bcddae-fb3c-46fa-b653-c279ff51f1c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='Surname-error']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Surname-error</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>dd078fbf-c1b8-4553-a926-ea7194735db0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Surname-error</value>
      <webElementGuid>c09e15f9-ae8e-4712-b38f-5478816be209</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please enter surname</value>
      <webElementGuid>8cd3bde4-379c-40b2-a06d-f1220e716b1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Surname-error&quot;)</value>
      <webElementGuid>98049639-6ca4-4dec-bef9-0d749902550a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='Surname-error']</value>
      <webElementGuid>eeb344ed-fee1-4b45-b859-7b4d8e1c58e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Surname'])[1]/following::span[2]</value>
      <webElementGuid>8ba6aaa7-8658-4f8c-8295-6dba80943c66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter first name'])[1]/following::span[2]</value>
      <webElementGuid>0164ddf7-07e9-4a74-8b97-2b1798e698d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E-post'])[1]/preceding::span[1]</value>
      <webElementGuid>6671ef91-5431-470f-b94b-9e8ba24f3382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobile'])[1]/preceding::span[2]</value>
      <webElementGuid>b9e54e53-a401-4604-b2df-1c62817fcae5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Please enter surname']/parent::*</value>
      <webElementGuid>470dfda7-0de8-42ca-9153-6a52aeceb1a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/span</value>
      <webElementGuid>36da448e-ef03-447b-98bc-db608391e7e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'Surname-error' and (text() = 'Please enter surname' or . = 'Please enter surname')]</value>
      <webElementGuid>0c286573-321e-49a3-9c0b-8a1d30345e5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
