<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtEpost</name>
   <tag></tag>
   <elementGuidId>c05ffe6b-41ee-4a17-bb03-6f5f251c6154</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='E_post']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#E_post</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a271cb2e-6c70-40ca-a5e6-a5c8270827a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-box single-line</value>
      <webElementGuid>6fce4dd5-fca3-4e6c-8ce5-7a5c1d7408e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>E_post</value>
      <webElementGuid>cf22ccf6-4fb3-4ce0-ab3b-a44660661191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>E_post</value>
      <webElementGuid>d13868d6-ffe1-4d87-84eb-89c8cc5b65cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7c3c9a6c-5cf6-4a4e-b56d-e2c647ab3313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;E_post&quot;)</value>
      <webElementGuid>3678c2df-4812-4303-be91-1363219f67e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='E_post']</value>
      <webElementGuid>f0423e28-18dd-4fb2-a802-d3dffeb02d9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>287f7f36-48ef-4fe5-a258-2425ad3b75d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'E_post' and @name = 'E_post' and @type = 'text']</value>
      <webElementGuid>392f33ad-845b-4060-8712-b1d24bbbdd06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
