<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Create New_searching</name>
   <tag></tag>
   <elementGuidId>bf1cc5d8-15d5-4611-9f49-2dd2905418ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searching']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#searching</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6ecc87c8-65aa-4f93-9769-7cd988c265f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searching</value>
      <webElementGuid>ed6e02d6-4ea3-4251-bc30-eae4f482b27c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>searching</value>
      <webElementGuid>efcd7ee7-2a19-4502-a3e6-efbea1c63ae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search Name or Email</value>
      <webElementGuid>bb8ad82c-e626-4834-a80a-44c0a22af856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a31d6d60-24f6-476c-9635-105e4d9fdee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searching&quot;)</value>
      <webElementGuid>466f2f75-2bba-4edc-a1f9-c744ba1b1730</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searching']</value>
      <webElementGuid>66a66738-e8ed-4e18-b245-c538c7270f64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/form/input</value>
      <webElementGuid>77eaeb8b-5e04-4687-8318-c9fc13730842</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'searching' and @name = 'searching' and @placeholder = 'Search Name or Email' and @type = 'text']</value>
      <webElementGuid>9ebf2887-f677-4b81-853d-e65d03350e98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
